#version: "3"

#services:
#  nginx:
#    container_name: nginx
#    image: nginx:alpine
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#    depends_on:
#      - api

#   api:
#     container_name: api
#     image: api:maven
#     build:
#       context: ./
#       dockerfile: Dockerfile
#     ports:
#       - 8080:8080
#     volumes:
#       - /var/app
#     restart: always

#   mongodb:
#     image: mongo
#     container_name: mongodb-dev
#     ports:
#       - 27017:27017
#     volumes:
#       - data:/data
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=rootuser
#       - MONGO_INITDB_ROOT_PASSWORD=rootpass
#   mongo-express:
#     image: mongo-express
#     container_name: mongo-express-dev
#     restart: always
#     ports:
#       - 8081:8081
#     environment:
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
#       - ME_CONFIG_MONGODB_SERVER=mongodb
# volumes:
#   data: {}
