version: "3.8"
services:
  frontend:
    build:
      context: src/main/react-client/
      dockerfile: Dockerfile
    container_name: frontend
    image: {$AWS_ACCOUNT_ID}.dkr.ecr.{$AWS_DEFAULT_REGION}.amazonaws.com/frontend-deploy
    ports:
      - 80:80
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    image: {$AWS_ACCOUNT_ID}.dkr.ecr.{$AWS_DEFAULT_REGION}.amazonaws.com/backend-deploy
    ports:
      - 8080:8080