# === to rebuild containers ===
# docker-compose down
# docker-compose up -d --build --force-recreate

version: "3.8"
services:
#  frontend:
##    image: frontend
##    image: 218046717840.dkr.ecr.us-east-1.amazonaws.com/frontend-deploy
#    container_name: frontend
##    hostname:
##    build: ./frontend
#    build:
#      context: src/main/react-client/
#      dockerfile: Dockerfile
#    ports:
#      - 80:80
##    depends_on:
##      - backend
##    networks:
##      - ultrasound-network

  ultrasound-server:
#    image: backend
#    image: 218046717840.dkr.ecr.us-east-1.amazonaws.com/backend-deploy
    container_name: ultrasound-server-cntr
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080

#version: "3.8"
#services:
#  mongodb:
#    image: mongo
#    container_name: mongodb-dev
#    ports:
#      - 27017:27017
#    volumes:
#      - data:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=rootuser
#      - MONGO_INITDB_ROOT_PASSWORD=rootpass
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express-dev
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
#  data: {}
